services:
    Github\Client:
        arguments:
            - '@Github\HttpClient\Builder'
        calls:
            - ['authenticate', ['%env(GITHUB_TOKEN)%', 'access_token_header']]

    Github\ResultPager:
        arguments: ['@Github\Client']

    Github\HttpClient\Builder:
        arguments:
            - '@github.httplug_client'
            - '@Http\Message\RequestFactory'
            - '@Http\Message\StreamFactory'

    github.httplug_client:
        class: Symfony\Component\HttpClient\HttplugClient
        arguments:
            - '@github.retryable_client'
            - '@Psr\Http\Message\ResponseFactoryInterface'
            - '@Psr\Http\Message\StreamFactoryInterface'

    github.retryable_client:
        class: Symfony\Component\HttpClient\RetryableHttpClient
        arguments:
            - '@http_client'
            - '@github.retry_strategy'
            - 2
            - '@logger'

    github.retry_strategy:
        class: Symfony\Component\HttpClient\Retry\GenericRetryStrategy
        arguments:
            - [0, 404, 423, 425, 429, 500, 502, 503, 504, 507, 510]
