name: carson-bot

type: php:7.3

runtime:
    extensions:
        - apcu
        - mbstring
        

build:
    flavor: none

web:
    locations:
        "/":
            root: "web"
            expires: 1h
            passthru: "/app.php"

disk: 2048

mounts:
    "app/cache": { source: local, source_path: "app/cache" }
    "app/logs": { source: local, source_path: "app/logs" }

hooks:
    build: |
        set -x -e

        # Remove the development front-controller if present
        (>&2 rm web/app_dev.php)

        SYMFONY_ENV=prod composer install --prefer-dist --optimize-autoloader --classmap-authoritative --no-progress --no-ansi --no-interaction --no-dev
        (>&2 SYMFONY_ENV=prod app/console cache:clear --no-warmup)
        (>&2 SYMFONY_ENV=prod app/console cache:warmup)

    deploy: |
        set -x -e

        (>&2 SYMFONY_ENV=prod app/console cache:clear --no-warmup)
        (>&2 SYMFONY_ENV=prod app/console cache:warmup)
