# listener services that you can opt into for a repository
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.

    app.subscriber.status_change_by_comment_subscriber:
        class: App\Subscriber\StatusChangeByCommentSubscriber
        public: true

    app.subscriber.status_change_on_push_subscriber:
        class: App\Subscriber\StatusChangeOnPushSubscriber
        public: true

    app.subscriber.needs_review_new_pr_subscriber:
        class: App\Subscriber\NeedsReviewNewPRSubscriber
        public: true

    app.subscriber.milestone_new_pr_subscriber:
        class: App\Subscriber\MilestoneNewPRSubscriber
        public: true

    app.subscriber.bug_label_new_issue_subscriber:
        class: App\Subscriber\BugLabelNewIssueSubscriber
        public: true

    app.subscriber.auto_label_pr_from_content_subscriber:
        class: App\Subscriber\AutoLabelPRFromContentSubscriber
        public: true

    app.subscriber.status_change_by_review_subscriber:
        class: App\Subscriber\StatusChangeByReviewSubscriber
        public: true

parameters:
    # point to the main symfony repositories
    repositories:
        symfony/symfony:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.status_change_by_review_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
                - app.subscriber.milestone_new_pr_subscriber
            # secret: change_me

        symfony/symfony-docs:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.status_change_on_push_subscriber
                - app.subscriber.status_change_by_review_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
                - app.subscriber.milestone_new_pr_subscriber
            # secret: %symfony_docs_secret%

        # used in a functional test
        weaverryan/symfony:
            subscribers:
                - app.subscriber.status_change_by_comment_subscriber
                - app.subscriber.status_change_on_push_subscriber
                - app.subscriber.status_change_by_review_subscriber
                - app.subscriber.needs_review_new_pr_subscriber
                - app.subscriber.bug_label_new_issue_subscriber
                - app.subscriber.auto_label_pr_from_content_subscriber
                - app.subscriber.milestone_new_pr_subscriber
