services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: false

    App\Subscriber\:
        resource: '../src/Subscriber/*'

parameters:
    env(SYMFONY_DOCS_SECRET): ''
    env(SYMFONY_SECRET): ''
    # point to the main symfony repositories
    repositories:
        symfony/symfony:
            subscribers:
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelPRFromContentSubscriber'
            secret: '%env(SYMFONY_SECRET)%'

        symfony/symfony-docs:
            subscribers:
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeOnPushSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelPRFromContentSubscriber'
            secret: '%env(SYMFONY_DOCS_SECRET)%'

        # used in a functional test
        weaverryan/symfony:
            subscribers:
                - 'App\Subscriber\StatusChangeByCommentSubscriber'
                - 'App\Subscriber\StatusChangeOnPushSubscriber'
                - 'App\Subscriber\StatusChangeByReviewSubscriber'
                - 'App\Subscriber\NeedsReviewNewPRSubscriber'
                - 'App\Subscriber\BugLabelNewIssueSubscriber'
                - 'App\Subscriber\AutoLabelPRFromContentSubscriber'
