imports:
    - { resource: github.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Subscriber,Kernel.php,GitHubEvents.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Github\Api\Issue:
        factory: ['@Github\Client', api]
        arguments: [issue]

    Github\Api\Issue\Labels:
        factory: ['@Github\Api\Issue', labels]

    Github\Api\Issue\Milestones:
        factory: ['@Github\Api\Issue', milestones]

    App\Issues\StatusApi: '@App\Issues\GitHub\GitHubStatusApi'

    App\Repository\Provider\InMemoryRepositoryProvider:
        arguments: [ '%repositories%' ]

    App\Repository\Provider\RepositoryProviderInterface: '@App\Repository\Provider\InMemoryRepositoryProvider'
