name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-7.4-${{ hashFiles('composer.*') }}
          restore-keys: |
            composer-${{ runner.os }}-7.4-
            composer-${{ runner.os }}-
            composer-

      - name: Download dependencies
        run: |
          composer install --no-interaction --optimize-autoloader
          ./vendor/bin/simple-phpunit install

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.CARSONTEST_GITHUB_TOKEN }}
        run: |
          if [ ! -z $GITHUB_TOKEN ]; then
              ./vendor/bin/simple-phpunit --testsuite Functional
          fi
          ./vendor/bin/simple-phpunit --testsuite Unit
