name: CI

on:
  pull_request: ~
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@2.7.0
        with:
          php-version: 7.4
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        run: |
          composer update --no-interaction --prefer-dist --optimize-autoloader
          ./vendor/bin/simple-phpunit install

      - name: Run tests
        env:
          SYMFONY_REQUIRE: 4.4.*
          GITHUB_TOKEN: ${{ secrets.CARSONTEST_GITHUB_TOKEN }}
        run: |
          ./vendor/bin/simple-phpunit
